In [1]:
import numpy as np

In [2]:
n_samples = 10
max_len = 5
max_int = n_samples*max_len
x = np.arange(n_samples*max_len).reshape((n_samples, max_len))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [3]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [4]:
y = np.zeros((n_samples, max_len, max_int))
y.shape

(10, 5, 50)

In [5]:
from keras.utils import np_utils

Using TensorFlow backend.


In [6]:
y_cat = np_utils.to_categorical(x, num_classes=max_int)
y_cat.shape

(10, 5, 50)

In [9]:
preds = np.random.rand(20,10,5)
preds.shape

(20, 10, 5)

In [14]:
decoded = np.zeros((preds.shape[0], preds.shape[1]))
decoded.shape

(20, 10)

In [19]:
for i in range(preds.shape[0]):
    for j in range(preds.shape[1]):
        decoded[i, j] = np.argmax(preds[i, j])

In [20]:
decoded

array([[2., 0., 3., 0., 3., 0., 1., 2., 2., 2.],
       [0., 1., 1., 3., 1., 1., 2., 2., 2., 4.],
       [0., 3., 2., 1., 1., 3., 1., 4., 2., 1.],
       [1., 1., 3., 4., 2., 4., 2., 0., 4., 4.],
       [3., 4., 0., 4., 1., 2., 1., 1., 0., 2.],
       [2., 1., 1., 0., 1., 0., 4., 4., 3., 1.],
       [1., 4., 3., 1., 1., 1., 4., 2., 4., 2.],
       [2., 4., 1., 0., 0., 3., 3., 0., 1., 1.],
       [0., 2., 2., 0., 4., 4., 2., 1., 3., 4.],
       [0., 0., 2., 4., 3., 3., 4., 4., 0., 2.],
       [3., 3., 0., 2., 4., 0., 4., 2., 1., 4.],
       [0., 0., 2., 1., 3., 1., 3., 4., 1., 1.],
       [0., 1., 2., 3., 2., 2., 4., 2., 2., 1.],
       [2., 3., 4., 1., 1., 1., 3., 4., 1., 0.],
       [0., 1., 1., 4., 0., 1., 1., 4., 3., 3.],
       [2., 1., 1., 2., 3., 0., 1., 0., 1., 4.],
       [1., 3., 0., 1., 1., 3., 2., 2., 3., 4.],
       [3., 1., 4., 4., 2., 0., 3., 0., 2., 1.],
       [1., 0., 1., 3., 2., 1., 0., 4., 0., 4.],
       [3., 1., 2., 1., 0., 0., 4., 3., 0., 2.]])

In [21]:
fn = 'preds_generative_.h5'
fn[fn.rfind('/'):fn.rfind('.')] + '.txt'

'.txt'